spring:
    application:
        name: product-catalog-service
        author: Alok Arora

    datasource:
        name: globomartdb
        driverClassName: org.h2.Driver
        initialize: true
        url: jdbc:h2:mem:globomart;DB_CLOSE_DELAY=-1

    h2:
        console.enabled: true

    jpa:
        properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: update

